appname: ci-demo

service:
  port: 8080

replicaCount: 2

image:
  repository: registry.cn-hangzhou.aliyuncs.com/gitops-demo/ci-demo 
  tag: 216-202411210758-55-b12b19f
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
